FROM controller-base

WORKDIR /usr/src/app
COPY ./container-sdx-controller /usr/src/app

# ENTRYPOINT ["python3"]
# CMD ["-m", "uvicorn", "sdx_controller.app:asgi_app", "--host", "0.0.0.0", "--port", "8080"]
